# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Plank by Pinterest
favicon: "assets/images/pinterest-dev-logo.png"
description: > # this means to ignore newlines until "baseurl:"
  Plank documentation site 

# Build settings
markdown: kramdown